{
 "title": "The Big Board",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "VTS",
    "query": "label_values(nginx_server_bytes, instance)"
   },
   {
    "name": "node",
    "label": "Server",
    "query": "label_values(node_exporter_build_info, instance)"
   },
   {
    "name": "Upstream",
    "query": "label_values(nginx_upstream_bytes{instance=~\"$Instance\"}, upstream)"
   },
   {
    "name": "nginx",
    "query": "label_values(nginx_http_requests_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "vulpine.club operational status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 } },
  {
   "title": "Load (1m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Disk (rootfs)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{device!~'tmpfs', device!~'by-uuid', instance=~'$node', mountpoint=\"/rootfs\"} / node_filesystem_size_bytes{device!~'tmpfs', device!~'by-uuid', instance=~'$node', mountpoint=\"/rootfs\"}) or 100.0 - 100 * (node_filesystem_avail{device!~'tmpfs',device!~'by-uuid',instance=~'$node', mountpoint=\"/rootfs\"} / node_filesystem_size{device!~'tmpfs',device!~'by-uuid',instance=~'$node', mountpoint=\"/rootfs\"})"
    }
   ]
  },
  {
   "title": "HTTP Reqs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[5m])) by (instance)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Toots per Second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(instance_status_count[13m])"
    }
   ]
  },
  {
   "title": "1xx status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(rate(nginx_server_requests{code=~\"1xx\", instance=~'$Instance'}[6h])) by (instance) / sum(rate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[6h])) by (instance)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "4xx status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(rate(nginx_server_requests{code=~\"4xx\", instance=~'$Instance'}[6h])) by (instance) / sum(rate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[6h])) by (instance)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Enqueued jobs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sidekiq_enqueued_jobs" }
   ]
  },
  {
   "title": "Retry jobs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sidekiq_retry_jobs" }
   ]
  },
  {
   "title": "2xx/3xx status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(rate(nginx_server_requests{code=~\"2xx|3xx\", instance=~'$Instance'}[6h])) by (instance) / sum(rate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[6h])) by (instance)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "5xx status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(rate(nginx_server_requests{code=~\"5xx\", instance=~'$Instance'}[6h])) by (instance) / sum(rate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[6h])) by (instance)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "instance_user_count" }
   ]
  },
  {
   "title": "Weekly logins",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "instance_week_login" }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_upstream_responseMsec{instance=~\"$Instance\", upstream=~\"^$Upstream$\", backend=~\".+:3000\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    },
    {
     "expr": "sum(nginx_upstream_responseMsec{instance=~\"$Instance\", upstream=~\"^$Upstream$\", backend=~\".+:4000\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=\"$nginx\"}",
     "legendFormat": "{{state}} (Active client connections including Waiting connections)",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "nginx_connections_reading{instance=\"$nginx\"}",
     "legendFormat": "{{state}} (Connections where nginx is reading the request header)"
    },
    {
     "expr": "nginx_connections_writing{instance=\"$nginx\"}",
     "legendFormat": "{{state}} (Connections where nginx is writing the response back to the client)"
    },
    {
     "expr": "nginx_connections_waiting{instance=\"$nginx\"}",
     "legendFormat": "{{state}} (Idle client connections waiting for a request)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"system\",instance=~'$node'}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"user\",instance=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"nice\",instance=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"iowait\",instance=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"steal\",instance=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"idle\",instance=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"irq\",instance=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"softirq\",instance=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"guest\",instance=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Queues latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(sidekiq_queue_latency_seconds[1m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(sidekiq_processed_jobs_total[1m])",
     "legendFormat": "processing rate"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_requests{instance=~\"$Instance\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    },
    {
     "expr": "100 * sum(irate(nginx_server_requests{instance=~\"$Instance\", code=~\"5xx\"}[5m])) / sum(irate(nginx_server_requests{instance=~\"$Instance\", code=\"total\"}[5m]))",
     "legendFormat": "error rate"
    },
    {
     "expr": "100 * sum(rate(nginx_server_requests{instance=~\"$Instance\", code=~\"5xx\"}[6h])) / sum(rate(nginx_server_requests{instance=~\"$Instance\", code=\"total\"}[6h]))",
     "legendFormat": "avg error rate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} ) or ( node_memory_MemTotal{instance=~'$node'} - node_memory_MemFree{instance=~'$node'} - node_memory_Buffers{instance=~'$node'} - node_memory_Cached{instance=~'$node'} - node_memory_SwapCached{instance=~'$node'} - node_memory_Slab{instance=~'$node'} - node_memory_PageTables{instance=~'$node'} - node_memory_VmallocUsed{instance=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'}) or (node_memory_SwapTotal{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node'} or node_memory_Cached{instance=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$node'} or node_memory_Buffers{instance=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node'} or node_memory_MemFree{instance=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~'$node'} or node_memory_Slab{instance=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$node'} or node_memory_SwapCached{instance=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~'$node'} or node_memory_PageTables{instance=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=~'$node'} or node_memory_VmallocUsed{instance=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~'$node'} or node_memory_Committed_AS{instance=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~'$node'} or node_memory_Mapped{instance=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~'$node'} or node_memory_Active{instance=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=~'$node'} or node_memory_Inactive{instance=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  { "title": "Mastodon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "instance_user_count" }
   ]
  },
  {
   "title": "Weekly logins",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "instance_week_login" }
   ]
  },
  {
   "title": "Weekly registrations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "instance_week_registrations" }
   ]
  },
  {
   "title": "Weekly toots",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "instance_week_toots" }
   ]
  },
  {
   "title": "Known instances",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 18 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "instance_domain_count" }
   ]
  },
  {
   "title": "Posts per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(instance_status_count[13m])*60",
     "legendFormat": "statuses"
    }
   ]
  },
  {
   "title": "Web Service Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
     "format": "reqps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[5m])) by (instance)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "1xx/2xx/3xx status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 * sum(rate(nginx_server_requests{code=~\"1xx|2xx|3xx\", instance=~'$Instance'}[6h])) by (instance) / sum(rate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[6h])) by (instance)",
       "legendFormat": "error rate"
      }
     ]
    },
    {
     "title": "4xx status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 * sum(rate(nginx_server_requests{code=~\"4xx\", instance=~'$Instance'}[6h])) by (instance) / sum(rate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[6h])) by (instance)",
       "legendFormat": "error rate"
      }
     ]
    },
    {
     "title": "5xx status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 * sum(rate(nginx_server_requests{code=~\"5xx\", instance=~'$Instance'}[6h])) by (instance) / sum(rate(nginx_server_requests{code=\"total\", instance=~'$Instance'}[6h])) by (instance)",
       "legendFormat": "error rate"
      }
     ]
    },
    {
     "title": "Server Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_server_requests{instance=~\"$Instance\", code!=\"total\"}[5m])) by (code)",
       "legendFormat": "{{ code }}"
      },
      {
       "expr": "100 * sum(irate(nginx_server_requests{instance=~\"$Instance\", code=~\"4xx|5xx\"}[5m])) / sum(irate(nginx_server_requests{instance=~\"$Instance\", code=\"total\"}[5m]))",
       "legendFormat": "error rate"
      },
      {
       "expr": "100 * sum(rate(nginx_server_requests{instance=~\"$Instance\", code=~\"4xx|5xx\"}[6h])) / sum(rate(nginx_server_requests{instance=~\"$Instance\", code=\"total\"}[6h]))",
       "legendFormat": "avg error rate"
      }
     ]
    },
    {
     "title": "Upstream Backend Response",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 9, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_upstream_responseMsec{instance=~\"$Instance\", upstream=~\"^$Upstream$\", backend=~\".+:3000\"}) by (backend)",
       "legendFormat": "{{ backend }}"
      },
      {
       "expr": "sum(nginx_upstream_responseMsec{instance=~\"$Instance\", upstream=~\"^$Upstream$\", backend=~\".+:4000\"}) by (backend)",
       "legendFormat": "{{ backend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Enqueued jobs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sidekiq_enqueued_jobs" }
     ]
    },
    {
     "title": "Retry jobs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sidekiq_retry_jobs" }
     ]
    },
    {
     "title": "Dead jobs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sidekiq_dead_jobs" }
     ]
    },
    {
     "title": "Queue enqueued jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      { "expr": "sidekiq_enqueued_jobs", "legendFormat": "jobs" }
     ]
    },
    {
     "title": "Queues latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(sidekiq_queue_latency_seconds[1m])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "rate(sidekiq_processed_jobs_total[1m])",
       "legendFormat": "processing rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "node",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100.0 - 100 * (node_filesystem_avail_bytes{device!~'tmpfs', device!~'by-uuid', instance=~'$node'} / node_filesystem_size_bytes{device!~'tmpfs', device!~'by-uuid', instance=~'$node'}) or 100.0 - 100 * (node_filesystem_avail{device!~'tmpfs',device!~'by-uuid',instance=~'$node'} / node_filesystem_size{device!~'tmpfs',device!~'by-uuid',instance=~'$node'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "repeat": "node",
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} ) or ( node_memory_MemTotal{instance=~'$node'} - node_memory_MemFree{instance=~'$node'} - node_memory_Buffers{instance=~'$node'} - node_memory_Cached{instance=~'$node'} - node_memory_SwapCached{instance=~'$node'} - node_memory_Slab{instance=~'$node'} - node_memory_PageTables{instance=~'$node'} - node_memory_VmallocUsed{instance=~'$node'} )",
       "legendFormat": "Apps"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~'$node'} or node_memory_Buffers{instance=~'$node'}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~'$node'} or node_memory_Cached{instance=~'$node'}",
       "legendFormat": "Cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~'$node'} or node_memory_MemFree{instance=~'$node'}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~'$node'} or node_memory_Slab{instance=~'$node'}",
       "legendFormat": "Slab"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~'$node'} or node_memory_SwapCached{instance=~'$node'}",
       "legendFormat": "SwapCached"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~'$node'} or node_memory_PageTables{instance=~'$node'}",
       "legendFormat": "PageTables"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=~'$node'} or node_memory_VmallocUsed{instance=~'$node'}",
       "legendFormat": "VmallocUsed"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'}) or (node_memory_SwapTotal{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
       "legendFormat": "Swap"
      },
      {
       "expr": "node_memory_Committed_AS_bytes{instance=~'$node'} or node_memory_Committed_AS{instance=~'$node'}",
       "legendFormat": "Committed"
      },
      {
       "expr": "node_memory_Mapped_bytes{instance=~'$node'} or node_memory_Mapped{instance=~'$node'}",
       "legendFormat": "Mapped"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~'$node'} or node_memory_Active{instance=~'$node'}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_Inactive_bytes{instance=~'$node'} or node_memory_Inactive{instance=~'$node'}",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "repeat": "node",
     "yaxes": [
      { "format": "short", "label": "%" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"system\",instance=~'$node'}[5m]))",
       "legendFormat": "system"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"user\",instance=~'$node'}[5m]))",
       "legendFormat": "user"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"nice\",instance=~'$node'}[5m]))",
       "legendFormat": "nice"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"iowait\",instance=~'$node'}[5m]))",
       "legendFormat": "iowait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"steal\",instance=~'$node'}[5m]))",
       "legendFormat": "steal"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"idle\",instance=~'$node'}[5m]))",
       "legendFormat": "idle"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"irq\",instance=~'$node'}[5m]))",
       "legendFormat": "irq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"softirq\",instance=~'$node'}[5m]))",
       "legendFormat": "softirq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"guest\",instance=~'$node'}[5m]))",
       "legendFormat": "guest"
      }
     ]
    }
   ]
  }
 ]
}