---
:concurrency: 25
:queues:
  - [default, 8]
  - [push, 6]
  - [pull, 4]
  - [mailers, 2]
  - [bulk]
:schedule:
  scheduled_statuses_scheduler:
    every: '5m'
    class: Scheduler::ScheduledStatusesScheduler
  destructing_statuses_scheduler:
    every: '1m'
    class: Scheduler::DestructingStatusesScheduler
  boosts_scheduler:
    every: '1m'
    class: Scheduler::BoostsScheduler
  domain_policy_scheduler:
    every: '15m'
    class: Scheduler::DomainPolicyScheduler
  janitor_scheduler:
    every: '1h'
    class: Scheduler::JanitorScheduler
  prune_database_scheduler:
    every: '1d'
    class: Scheduler::PruneDatabaseScheduler
  werewolf_scheduler:
    every: '1h'
    class: Scheduler::WerewolfScheduler
  media_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * *'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
  user_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(4..6) %> * * *'
    class: Scheduler::UserCleanupScheduler
  ip_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::IpCleanupScheduler
  filter_cleanup_scheduler:
    every: '15m'
    class: Scheduler::FilterCleanupScheduler
  email_scheduler:
    cron: '0 10 * * 2'
    class: Scheduler::EmailScheduler
  backup_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::BackupCleanupScheduler
  pghero_scheduler:
    cron: '0 0 * * *'
    class: Scheduler::PgheroScheduler
