#!/bin/bash

NEWFILE=.hourly.$(date -Iseconds).pgdump

(
    flock -n 9 || exit 1

    cd /srv/mastodon/vulpine.club/mastodon && \
    docker-compose run --rm dbbackup sh -c " \
        umask 0377 &&
        rm -f /dump/.hourly.*.pgdump &&
        pg_dump -Fc -Z0 -h db -d postgres -U postgres -f /dump/${NEWFILE} &&
        mv /dump/hourly.pgdump /dump/hourly.pgdump.0 &&
        mv /dump/${NEWFILE} /dump/hourly.pgdump"

) 9>/var/lock/mastodon.pg_dump

