#!/bin/bash
#
# Note: .mastodon-pingurl should contain one URL, which will be hit when
# this process completes successfully.
#
# This should be a HTTP (not HTTPS) URL because the 'web' container doesn't
# have enough smartz to verify certificates and idgaf atm

NEWFILE=.hourly.$(date -Iseconds).pgdump

(
    flock -n 9 || exit 1

    cd /srv/mastodon/vulpine.club/mastodon && \
    docker-compose run --rm dbbackup sh -c " \
        umask 0377 &&
        rm -f /dump/.hourly.*.pgdump &&
        pg_dump -Fc -Z0 -h db -d postgres -U postgres -f /dump/${NEWFILE} &&
        mv /dump/hourly.pgdump /dump/hourly.pgdump.0 &&
        mv /dump/${NEWFILE} /dump/hourly.pgdump"

    docker-compose run --rm web sh -c "\
        wget -O /dev/null \"$(cat `dirname $0`/.mastodon-pingurl)\""

) 9>/var/lock/mastodon.pg_dump

