#!/bin/bash
#
# Note: .mastodon-pingurl should contain one URL, which will be hit when
# this process completes successfully.
#
# This should be a HTTP (not HTTPS) URL because the 'web' container doesn't
# have enough smartz to verify certificates and idgaf atm

(
    flock -n 9 || exit 1

    cd /srv/mastodon/vulpine.club/mastodon && \
    docker-compose run --rm dbbackup sh -c " \
	    umask 0377 &&
	    pg_dump -Fc -h db -d postgres -U postgres -f /dump/hourly.$(date -Iseconds).pgdump && \
	    wget -O /dev/null \"$(cat `dirname $0`/.mastodon-pingurl)\""

) 9>/var/lock/mastodon.pg_dump

