#!/bin/bash
#
# Note: .mastodon-pingurl should contain one URL, which will be hit when
# this process completes successfully.
#
# This should be a HTTP (not HTTPS) URL because the 'web' container doesn't
# have enough smartz to verify certificates and idgaf atm

TARGET=/srv/mastodon/vulpine.club/pg_dump

(
    flock -w 7200 9 || exit 1

    echo "Snapshotting backup..."

    cd ${TARGET} &&
    mv daily.pgdump daily.pgdump.0 &&
    ln hourly.pgdump daily.pgdump &&
    rm daily.pgdump.0

    ls -la ${TARGET}

) 9>/var/lock/mastodon.pg_dump

echo "Removing remote media..."

cd /srv/mastodon/vulpine.club/mastodon && \
docker-compose run --rm web sh -c " \
    bundle exec bin/tootctl media remove" && \
docker-compose run --rm web sh -c "\
    wget -O /dev/null \"$(cat `dirname $0`/.mastodon-pingurl)\""

