#!/bin/bash

TARGET=/srv/mastodon/vulpine.club/pg_dump

(
    flock -w 7200 9 || exit 1

    echo "Snapshotting backup..."

    cd ${TARGET} &&
    mv daily.pgdump daily.pgdump.0 &&
    ln hourly.pgdump daily.pgdump &&
    rm daily.pgdump.0

    ls -la ${TARGET}

) 9>/var/lock/mastodon.pg_dump

echo "Removing remote media..."

cd /srv/mastodon/vulpine.club/mastodon && \
docker-compose run --rm web sh -c " \
    bundle exec bin/tootctl media remove --background"

