#!/bin/bash
#
# Note: .mastodon-pingurl should contain one URL, which will be hit when
# this process completes successfully.
#
# This should be a HTTP (not HTTPS) URL because the 'web' container doesn't
# have enough smartz to verify certificates and idgaf atm

find /srv/mastodon/vulpine.club/pg_dump/ -type f -name daily.* -mtime +7 -delete

cd /home/rtucker/dev/mastodon && \
docker-compose run --rm dbmaint sh -c " \
	umask 0377 &&
	pg_dump -Fc -h db -d postgres -U postgres -f /dump/daily.$(date -Iseconds).pgdump" && \
docker-compose run --rm web sh -c "\
	rake mastodon:daily && \
	wget -O /dev/null \"$(cat `dirname $0`/.mastodon-pingurl)\""

